spring:
  application:
    name: mar-sem-lixo-api
  threads:
    virtual:
      enabled: true
  profiles:
    default: dev

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.marsemlixo: DEBUG
    org.springframework.web: INFO

management:
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.marsemlixo: INFO
    org.springframework: WARN

management:
  endpoint:
    health:
      show-details: never
